/**
 * Labeling page for reviewing auto-labeled benchmark questions.
 * Auto-labels are generated by hybrid error analysis (programmatic + LLM).
 * Users can override any auto-label with their own assessment.
 */

import { useState, useMemo } from "react"
import { ArrowLeft, ChevronLeft, ChevronRight, ChevronDown, GitCompare, Check, AlertCircle, Bot, User } from "lucide-react"
import { format as formatSqlLib } from "sql-formatter"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { SqlCodeBlock } from "@/components/SqlCodeBlock"
import { SqlDiffView } from "@/components/SqlDiffView"
import { DataTable } from "@/components/DataTable"
import { getSelectedBenchmarkQuestions, getExpectedSql } from "@/lib/benchmarkUtils"
import type { SqlExecutionResult, AutoLabelResult } from "@/types"

interface LabelingPageProps {
  genieSpaceId: string
  spaceData: Record<string, unknown>
  selectedQuestions: string[]
  // Lifted state (persists across navigation)
  currentIndex: number
  generatedSql: Record<string, string>
  genieResults: Record<string, SqlExecutionResult | null>
  expectedResults: Record<string, SqlExecutionResult | null>
  correctAnswers: Record<string, boolean | null>
  feedbackTexts: Record<string, string>
  processingErrors: Record<string, string>
  // Auto-labeling state
  autoLabelResults: Record<string, AutoLabelResult>
  userOverrides: Record<string, boolean>
  overrideReasons: Record<string, string>
  // Actions
  onSetCurrentIndex: (index: number) => void
  onSetCorrectAnswer: (questionId: string, answer: boolean | null) => void
  onSetFeedbackText: (questionId: string, text: string) => void
  onSetUserOverride: (questionId: string, disagrees: boolean) => void
  onSetOverrideReason: (questionId: string, reason: string) => void
  onBack: () => void
  onFinish: () => void
}

function AutoLabelBadge({ result }: { result: AutoLabelResult }) {
  const colors = {
    correct: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
    incorrect: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
    inconclusive: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  }

  return (
    <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${colors[result.auto_label]}`}>
      <Bot className="w-3 h-3" />
      <span className="capitalize">{result.auto_label}</span>
      <span className="opacity-60">({result.method})</span>
    </div>
  )
}

export function LabelingPage({
  genieSpaceId,
  spaceData,
  selectedQuestions,
  currentIndex,
  generatedSql,
  genieResults,
  expectedResults,
  correctAnswers,
  feedbackTexts,
  processingErrors,
  autoLabelResults,
  userOverrides,
  overrideReasons,
  onSetCurrentIndex,
  onSetCorrectAnswer,
  onSetFeedbackText,
  onSetUserOverride,
  onSetOverrideReason,
  onBack,
  onFinish,
}: LabelingPageProps) {
  const [showDiff, setShowDiff] = useState(false)

  const questions = useMemo(
    () => getSelectedBenchmarkQuestions(spaceData, selectedQuestions),
    [spaceData, selectedQuestions]
  )

  const totalQuestions = questions.length
  const currentQuestion = questions[currentIndex]

  // Count ready-to-finish: auto-labeled (not inconclusive) OR manually labeled
  const readyCount = questions.filter(q => {
    const autoResult = autoLabelResults[q.id]
    const isManuallyLabeled = correctAnswers[q.id] !== undefined && correctAnswers[q.id] !== null
    if (autoResult && autoResult.auto_label !== "inconclusive") {
      return true // Auto-labeled items are always ready
    }
    return isManuallyLabeled // Inconclusive or no auto-label needs manual
  }).length

  const canFinish = readyCount === totalQuestions && totalQuestions > 0

  const handlePrev = () => onSetCurrentIndex(Math.max(0, currentIndex - 1))
  const handleNext = () => onSetCurrentIndex(Math.min(totalQuestions - 1, currentIndex + 1))
  const handleSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => onSetCurrentIndex(Number(e.target.value))
  const handleSegmentClick = (idx: number) => onSetCurrentIndex(idx)

  const expectedSql = useMemo(() => getExpectedSql(currentQuestion), [currentQuestion])
  const currentGeneratedSql = currentQuestion ? generatedSql[currentQuestion.id] : null
  const currentError = currentQuestion ? processingErrors[currentQuestion.id] : null
  const genieResult = currentQuestion ? genieResults[currentQuestion.id] ?? null : null
  const expectedResult = currentQuestion ? expectedResults[currentQuestion.id] ?? null : null
  const isCorrect = currentQuestion ? correctAnswers[currentQuestion.id] ?? null : null
  const feedbackText = currentQuestion ? feedbackTexts[currentQuestion.id] ?? '' : ''
  const autoResult = currentQuestion ? autoLabelResults[currentQuestion.id] : undefined
  const isOverridden = currentQuestion ? userOverrides[currentQuestion.id] === true : false
  const overrideReason = currentQuestion ? overrideReasons[currentQuestion.id] ?? '' : ''

  const formatSql = (sql: string): string => {
    try {
      return formatSqlLib(sql, {
        language: "sql",
        indentStyle: "standard",
        keywordCase: "upper",
        linesBetweenQueries: 1,
      })
    } catch {
      return sql
    }
  }

  const formattedGeneratedSql = currentGeneratedSql ? formatSql(currentGeneratedSql) : null

  if (!currentQuestion) {
    return (
      <div className="space-y-6 animate-slide-up">
        <div className="flex items-center gap-4">
          <Button variant="outline" onClick={onBack}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Benchmarks
          </Button>
        </div>
        <Card>
          <CardContent className="py-12 text-center">
            <p className="text-muted">No questions selected.</p>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-display font-bold text-primary">
            Review Auto-Labels
          </h1>
          <p className="text-muted">
            Space ID: <span className="font-mono text-secondary">{genieSpaceId}</span>
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={onBack}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Benchmarks
          </Button>
        </div>
      </div>

      {/* Segmented Progress Bar */}
      <div className="space-y-2">
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={handlePrev} disabled={currentIndex === 0}>
            <ChevronLeft className="w-4 h-4 mr-1" />
            Prev
          </Button>

          <div className="flex-1 flex gap-1">
            {questions.map((q, idx) => {
              const qAutoResult = autoLabelResults[q.id]
              const qIsOverridden = userOverrides[q.id] === true
              const labelValue = correctAnswers[q.id]
              const isLabeled = labelValue !== undefined && labelValue !== null
              const isCurrent = idx === currentIndex
              const hasError = processingErrors[q.id]

              let bgClass = "bg-elevated hover:bg-secondary/30"
              let title = `Question ${idx + 1}`

              if (qAutoResult) {
                if (qAutoResult.auto_label === "correct") {
                  bgClass = "bg-green-500 dark:shadow-[0_0_8px_rgba(34,197,94,0.5)]"
                  title += " (auto: correct)"
                } else if (qAutoResult.auto_label === "incorrect") {
                  bgClass = "bg-red-500 dark:shadow-[0_0_8px_rgba(239,68,68,0.5)]"
                  title += " (auto: incorrect)"
                } else {
                  bgClass = "bg-amber-500 dark:shadow-[0_0_8px_rgba(245,158,11,0.5)]"
                  title += " (inconclusive)"
                }
              } else if (isLabeled) {
                bgClass = labelValue === true
                  ? "bg-green-500 dark:shadow-[0_0_8px_rgba(34,197,94,0.5)]"
                  : "bg-red-500 dark:shadow-[0_0_8px_rgba(239,68,68,0.5)]"
                title += labelValue ? " (correct)" : " (incorrect)"
              } else if (hasError) {
                bgClass = "bg-amber-500 dark:shadow-[0_0_8px_rgba(245,158,11,0.5)]"
                title += " (error)"
              }

              return (
                <button
                  key={q.id}
                  onClick={() => handleSegmentClick(idx)}
                  className={`
                    flex-1 h-2.5 rounded-full transition-all cursor-pointer
                    ${bgClass}
                    ${isCurrent ? "ring-2 ring-accent ring-offset-2 ring-offset-surface" : ""}
                    ${qIsOverridden ? "ring-2 ring-blue-500 ring-offset-1 ring-offset-surface" : ""}
                  `}
                  title={title + (qIsOverridden ? " (overridden)" : "")}
                />
              )
            })}
          </div>

          <Button variant="outline" size="sm" onClick={handleNext} disabled={currentIndex === totalQuestions - 1}>
            Next
            <ChevronRight className="w-4 h-4 ml-1" />
          </Button>

          <Button size="sm" disabled={!canFinish} onClick={onFinish}>
            <Check className="w-4 h-4 mr-1" />
            Finish
          </Button>
        </div>

        <p className="text-center text-sm text-muted">
          {readyCount} of {totalQuestions} ready
        </p>
      </div>

      {/* Question Display */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-3">
              <h3 className="text-sm font-medium text-muted">Question</h3>
              {autoResult && <AutoLabelBadge result={autoResult} />}
            </div>
            <div className="relative">
              <select
                value={currentIndex}
                onChange={handleSelectChange}
                className="appearance-none text-sm text-secondary bg-elevated hover:bg-sunken pl-3 pr-8 py-1.5 rounded-lg cursor-pointer focus:outline-none focus:ring-2 focus:ring-accent/50 transition-colors"
              >
                {questions.map((q, idx) => {
                  const text = q.question.join(" ")
                  const truncated = text.length > 40 ? text.slice(0, 40) + "..." : text
                  return (
                    <option key={q.id} value={idx}>
                      {idx + 1}. {truncated}
                    </option>
                  )
                })}
              </select>
              <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 text-muted pointer-events-none" />
            </div>
          </div>
          <p className="text-primary text-lg">
            {currentQuestion.question.join(" ")}
          </p>
          {/* Auto-label reason */}
          {autoResult && (
            <p className="text-sm text-muted mt-2 italic">
              {autoResult.reason}
            </p>
          )}
        </CardContent>
      </Card>

      {/* Error display */}
      {currentError && (
        <Card className="border-amber-500/50 bg-amber-500/5">
          <CardContent className="py-4">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-amber-600 dark:text-amber-400">
                  Failed to process this question
                </p>
                <p className="text-sm text-muted mt-1">{currentError}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Review / Override Section */}
      <Card className={!genieResult && !currentError ? 'opacity-50' : ''}>
        <CardContent className="py-4 px-4">
          {autoResult && autoResult.auto_label !== "inconclusive" ? (
            /* Auto-labeled: Agree/Disagree flow */
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-semibold text-primary">Do you agree with the auto-label?</h3>
              </div>
              <div className="flex flex-col md:flex-row gap-4">
                <div>
                  <div className="flex gap-2">
                    <button
                      onClick={() => {
                        onSetUserOverride(currentQuestion.id, false)
                      }}
                      className={`px-3 py-1.5 text-sm rounded-lg border transition-colors flex items-center gap-1.5 ${
                        !isOverridden
                          ? 'border-accent bg-accent/10 text-accent'
                          : 'border-default text-secondary hover:border-strong'
                      }`}
                    >
                      <Check className="w-3.5 h-3.5" />
                      Agree
                    </button>
                    <button
                      onClick={() => {
                        onSetUserOverride(currentQuestion.id, true)
                        // When disagreeing, flip the auto-label
                        if (autoResult.auto_label === "correct") {
                          onSetCorrectAnswer(currentQuestion.id, false)
                        } else {
                          onSetCorrectAnswer(currentQuestion.id, true)
                        }
                      }}
                      className={`px-3 py-1.5 text-sm rounded-lg border transition-colors flex items-center gap-1.5 ${
                        isOverridden
                          ? 'border-blue-500 bg-blue-500/10 text-blue-600 dark:text-blue-400'
                          : 'border-default text-secondary hover:border-strong'
                      }`}
                    >
                      <User className="w-3.5 h-3.5" />
                      Disagree
                    </button>
                  </div>
                </div>

                {isOverridden && (
                  <div className="flex-1 space-y-2">
                    <div className="flex gap-2 items-center">
                      <label className="text-sm text-secondary">Your label:</label>
                      <button
                        onClick={() => onSetCorrectAnswer(currentQuestion.id, true)}
                        className={`px-2 py-1 text-xs rounded border transition-colors ${
                          isCorrect === true
                            ? 'border-green-500 bg-green-500/10 text-green-600 dark:text-green-400'
                            : 'border-default text-secondary hover:border-strong'
                        }`}
                      >
                        Correct
                      </button>
                      <button
                        onClick={() => onSetCorrectAnswer(currentQuestion.id, false)}
                        className={`px-2 py-1 text-xs rounded border transition-colors ${
                          isCorrect === false
                            ? 'border-red-500 bg-red-500/10 text-red-600 dark:text-red-400'
                            : 'border-default text-secondary hover:border-strong'
                        }`}
                      >
                        Incorrect
                      </button>
                    </div>
                    <textarea
                      value={overrideReason}
                      onChange={(e) => onSetOverrideReason(currentQuestion.id, e.target.value)}
                      placeholder="Why do you disagree?"
                      className="w-full p-2 text-sm rounded-lg border border-default bg-surface text-primary placeholder:text-muted resize-none focus:outline-none focus:ring-2 focus:ring-accent/50 transition-colors"
                      rows={2}
                    />
                  </div>
                )}
              </div>
            </div>
          ) : (
            /* Inconclusive or no auto-label: Manual labeling flow (same as original) */
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-sm font-semibold text-primary">
                  {autoResult?.auto_label === "inconclusive" ? "Manual Label Required" : "Label This Question"}
                </h3>
                {!genieResult && !currentError && (
                  <span className="text-xs text-muted">No results available</span>
                )}
              </div>
              <div className="flex flex-col md:flex-row gap-4">
                <div>
                  <label className="text-sm text-secondary mb-2 block">Was Genie's output correct?</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => onSetCorrectAnswer(currentQuestion.id, true)}
                      disabled={!genieResult && !currentError}
                      className={`px-3 py-1.5 text-sm rounded-lg border transition-colors ${
                        isCorrect === true
                          ? 'border-accent bg-accent/10 text-accent'
                          : 'border-default text-secondary hover:border-strong'
                      } disabled:cursor-not-allowed disabled:hover:border-default`}
                    >
                      Yes
                    </button>
                    <button
                      onClick={() => onSetCorrectAnswer(currentQuestion.id, false)}
                      disabled={!genieResult && !currentError}
                      className={`px-3 py-1.5 text-sm rounded-lg border transition-colors ${
                        isCorrect === false
                          ? 'border-accent bg-accent/10 text-accent'
                          : 'border-default text-secondary hover:border-strong'
                      } disabled:cursor-not-allowed disabled:hover:border-default`}
                    >
                      No
                    </button>
                  </div>
                </div>
                <div className="flex-1">
                  <label className="text-sm text-secondary mb-2 block">If not, what did Genie get wrong?</label>
                  <textarea
                    value={feedbackText}
                    onChange={(e) => onSetFeedbackText(currentQuestion.id, e.target.value)}
                    placeholder="Describe what was incorrect..."
                    disabled={!genieResult && !currentError}
                    className="w-full p-2 text-sm rounded-lg border border-default bg-surface text-primary placeholder:text-muted resize-none focus:outline-none focus:ring-2 focus:ring-accent/50 transition-colors disabled:cursor-not-allowed disabled:bg-elevated"
                    rows={2}
                  />
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Side-by-side Output Display */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted">Genie's Output</h3>
          <Card>
            <CardContent className="py-4">
              {genieResult ? (
                genieResult.error ? (
                  <div className="text-danger text-sm py-4 text-center">{genieResult.error}</div>
                ) : (
                  <DataTable columns={genieResult.columns} data={genieResult.data} truncated={genieResult.truncated} />
                )
              ) : currentError ? (
                <div className="text-center py-8">
                  <AlertCircle className="w-8 h-8 text-amber-500 mx-auto mb-2" />
                  <p className="text-amber-500 text-sm">Processing failed</p>
                </div>
              ) : (
                <p className="text-muted text-sm text-center py-8">No results available</p>
              )}
            </CardContent>
          </Card>
        </div>

        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted">Expected Output</h3>
          <Card>
            <CardContent className="py-4">
              {expectedResult ? (
                expectedResult.error ? (
                  <div className="text-danger text-sm py-4 text-center">{expectedResult.error}</div>
                ) : (
                  <DataTable columns={expectedResult.columns} data={expectedResult.data} truncated={expectedResult.truncated} />
                )
              ) : expectedSql ? (
                <p className="text-muted text-sm text-center py-8">No results available</p>
              ) : (
                <p className="text-muted text-sm text-center py-8">No expected SQL available</p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Side-by-side SQL Display */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted">Genie's Generated SQL</h3>
          {formattedGeneratedSql ? (
            <SqlCodeBlock code={formattedGeneratedSql} maxLines={15} />
          ) : currentError ? (
            <Card>
              <CardContent className="py-8 text-center">
                <AlertCircle className="w-6 h-6 text-amber-500 mx-auto mb-2" />
                <p className="text-amber-500 text-sm">Processing failed</p>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardContent className="py-8 text-center">
                <p className="text-muted text-sm">No SQL generated</p>
              </CardContent>
            </Card>
          )}
        </div>

        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted">Expected SQL</h3>
          {expectedSql ? (
            <SqlCodeBlock code={expectedSql} maxLines={15} />
          ) : (
            <Card>
              <CardContent className="py-8 text-center">
                <p className="text-muted text-sm">No expected SQL available</p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Diff View */}
      {formattedGeneratedSql && expectedSql && (
        <div className="space-y-3">
          <button
            onClick={() => setShowDiff(!showDiff)}
            className="flex items-center gap-2 text-sm font-medium text-secondary hover:text-primary transition-colors"
          >
            <GitCompare className="w-4 h-4" />
            <span>Show Diff View</span>
            <ChevronDown className={`w-4 h-4 transition-transform ${showDiff ? "rotate-180" : ""}`} />
          </button>
          {showDiff && (
            <SqlDiffView generatedSql={formattedGeneratedSql} expectedSql={expectedSql} />
          )}
        </div>
      )}
    </div>
  )
}
